<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Section;
use App\Models\Subject;

class SectionAndClassTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sections = [
            [
                'name'=>'Nursery',
                'classes'=>[
                    [
                        'name'=>'Nursery 1 Yellow','subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'N1Y'
                    ],
                    [
                        'name'=>'Nursery 1 Ash',
                        'subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'N1A'
                    ],
                    [
                        'name'=>'Nursery 1 Orange',
                        'subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'N1O'
                        ],
                        [
                            'name'=>'Nursery 2 Yellow','subjects'=>[
                                "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                            ],
                            'code'=>'N2Y'
                        ],
                        [
                            'name'=>'Nursery 2 Ash',
                            'subjects'=>[
                                "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                            ],
                            'code'=>'N2A'
                        ],
                        [
                            'name'=>'Nursery 2 Orange',
                            'subjects'=>[
                                "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                            ],
                            'code'=>'N2O'
                            ],
                            [
                                'name'=>'Nursery 3 Yellow','subjects'=>[
                                    "Alqur'an",
                                    "Mathematics",
                                    "English Studies",
                                    "basic Science and Technology",
                                    "CCA",
                                    "Handwriting",
                                    "IRK",
                                    "Al,azkar",
                                    "Al-arabiyya",
                                    "Al-huruf",
                                    "Al-kitaba",
                                    "Alhadith",
                                    "Ulumul Amma",
                                    "RNV",
                                    "PVS",
                                    "Hausa",
                                ],
                                'code'=>'N3Y'
                            ],
                            [
                                'name'=>'Nursery 3 Ash',
                                'subjects'=>[
                                    "Alqur'an",
                                    "Mathematics",
                                    "English Studies",
                                    "basic Science and Technology",
                                    "CCA",
                                    "Handwriting",
                                    "IRK",
                                    "Al,azkar",
                                    "Al-arabiyya",
                                    "Al-huruf",
                                    "Al-kitaba",
                                    "Alhadith",
                                    "Ulumul Amma",
                                    "RNV",
                                    "PVS",
                                    "Hausa",
                                ],
                                'code'=>'N3A'
                            ],
                            [
                                'name'=>'Nursery 3 Orange',
                                'subjects'=>[
                                    "Alqur'an",
                                    "Mathematics",
                                    "English Studies",
                                    "basic Science and Technology",
                                    "CCA",
                                    "Handwriting",
                                    "IRK",
                                    "Al,azkar",
                                    "Al-arabiyya",
                                    "Al-huruf",
                                    "Al-kitaba",
                                    "Alhadith",
                                    "Ulumul Amma",
                                    "RNV",
                                    "PVS",
                                    "Hausa",
                                ],
                                'code'=>'N3O'
                            ]
                ]
            ],
            [
                'name'=>'Basic',
                'classes'=>[
                    [
                        'name'=>'Basic 1 yellow','subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'B1Y'
                    ],
                    [
                        'name'=>'Basic 1 Ash',
                        'subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'B1A'
                    ],
                    [
                        'name'=>'Basic 1 Orange',
                        'subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'B1O'
                    ],
                    [
                        'name'=>'Basic 2 yellow','subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'B2Y'
                    ],
                    [
                        'name'=>'Basic 2 Ash',
                        'subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'B2A'
                    ],
                    [
                        'name'=>'Basic 2 Orange',
                        'subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'B2O'
                    ],
                    [
                        'name'=>'Basic 3 yellow','subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'B3Y'
                    ],
                    [
                        'name'=>'Basic 3 Ash',
                        'subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'B3A'
                    ],
                    [
                        'name'=>'Basic 3 Orange',
                        'subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'B3O'
                        ],
                        [
                            'name'=>'Basic 4 yellow','subjects'=>[
                                "Alqur'an",
                                "Mathematics",
                                "English Studies",
                                "basic Science and Technology",
                                "CCA",
                                "Handwriting",
                                "IRK",
                                "Al,azkar",
                                "Al-arabiyya",
                                "Al-huruf",
                                "Al-kitaba",
                                "Alhadith",
                                "Ulumul Amma",
                                "RNV",
                                "PVS",
                                "Hausa",
                            ],
                            'code'=>'B4Y'
                        ],
                        [
                            'name'=>'Basic 4 Ash',
                            'subjects'=>[
                                "Alqur'an",
                                "Mathematics",
                                "English Studies",
                                "basic Science and Technology",
                                "CCA",
                                "Handwriting",
                                "IRK",
                                "Al,azkar",
                                "Al-arabiyya",
                                "Al-huruf",
                                "Al-kitaba",
                                "Alhadith",
                                "Ulumul Amma",
                                "RNV",
                                "PVS",
                                "Hausa",
                            ],
                            'code'=>'B4A'
                        ],
                        [
                            'name'=>'Basic 4 Orange',
                            'subjects'=>[
                                "Alqur'an",
                                "Mathematics",
                                "English Studies",
                                "basic Science and Technology",
                                "CCA",
                                "Handwriting",
                                "IRK",
                                "Al,azkar",
                                "Al-arabiyya",
                                "Al-huruf",
                                "Al-kitaba",
                                "Alhadith",
                                "Ulumul Amma",
                                "RNV",
                                "PVS",
                                "Hausa",
                            ],
                            'code'=>'B4O'
                            ],
                            [
                                'name'=>'Basic 5 yellow','subjects'=>[
                                    "Alqur'an",
                                    "Mathematics",
                                    "English Studies",
                                    "basic Science and Technology",
                                    "CCA",
                                    "Handwriting",
                                    "IRK",
                                    "Al,azkar",
                                    "Al-arabiyya",
                                    "Al-huruf",
                                    "Al-kitaba",
                                    "Alhadith",
                                    "Ulumul Amma",
                                    "RNV",
                                    "PVS",
                                    "Hausa",
                                ],
                                'code'=>'B5Y'
                            ],
                            [
                                'name'=>'Basic 5 Ash',
                                'subjects'=>[
                                    "Alqur'an",
                                    "Mathematics",
                                    "English Studies",
                                    "basic Science and Technology",
                                    "CCA",
                                    "Handwriting",
                                    "IRK",
                                    "Al,azkar",
                                    "Al-arabiyya",
                                    "Al-huruf",
                                    "Al-kitaba",
                                    "Alhadith",
                                    "Ulumul Amma",
                                    "RNV",
                                    "PVS",
                                    "Hausa",
                                ],
                                'code'=>'B5A'
                            ],
                            [
                                'name'=>'Basic 5 Orange',
                                'subjects'=>[
                                    "Alqur'an",
                                    "Mathematics",
                                    "English Studies",
                                    "basic Science and Technology",
                                    "CCA",
                                    "Handwriting",
                                    "IRK",
                                    "Al,azkar",
                                    "Al-arabiyya",
                                    "Al-huruf",
                                    "Al-kitaba",
                                    "Alhadith",
                                    "Ulumul Amma",
                                    "RNV",
                                    "PVS",
                                    "Hausa",
                                ],
                                'code'=>'B5O'
                                ],
                                [
                                    'name'=>'Basic 6 yellow','subjects'=>[
                                        "Alqur'an",
                                        "Mathematics",
                                        "English Studies",
                                        "basic Science and Technology",
                                        "CCA",
                                        "Handwriting",
                                        "IRK",
                                        "Al,azkar",
                                        "Al-arabiyya",
                                        "Al-huruf",
                                        "Al-kitaba",
                                        "Alhadith",
                                        "Ulumul Amma",
                                        "RNV",
                                        "PVS",
                                        "Hausa",
                                    ],
                                    'code'=>'B6Y'
                                ],
                                [
                                    'name'=>'Basic 6 Ash',
                                    'subjects'=>[
                                        "Alqur'an",
                                        "Mathematics",
                                        "English Studies",
                                        "basic Science and Technology",
                                        "CCA",
                                        "Handwriting",
                                        "IRK",
                                        "Al,azkar",
                                        "Al-arabiyya",
                                        "Al-huruf",
                                        "Al-kitaba",
                                        "Alhadith",
                                        "Ulumul Amma",
                                        "RNV",
                                        "PVS",
                                        "Hausa",
                                    ],
                                    'code'=>'B6A'
                                ],
                                [
                                    'name'=>'Basic 6 Orange',
                                    'subjects'=>[
                                        "Alqur'an",
                                        "Mathematics",
                                        "English Studies",
                                        "basic Science and Technology",
                                        "CCA",
                                        "Handwriting",
                                        "IRK",
                                        "Al,azkar",
                                        "Al-arabiyya",
                                        "Al-huruf",
                                        "Al-kitaba",
                                        "Alhadith",
                                        "Ulumul Amma",
                                        "RNV",
                                        "PVS",
                                        "Hausa",
                                    ],
                                    'code'=>'B6O'
                                ]
                ]
            ],
            [
                'name'=>'Secondary',
                'classes'=>[
                    [
                        'name'=>'JSS 1 Yellow',
                        'subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'S1Y'
                        ],
                    [
                        'name'=>'JSS 1 Ash',
                        'subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'S1A'
                    ],
                    [
                        'name'=>'JSS 1 Orange',
                        'subjects'=>[
                            "Alqur'an",
                            "Mathematics",
                            "English Studies",
                            "basic Science and Technology",
                            "CCA",
                            "Handwriting",
                            "IRK",
                            "Al,azkar",
                            "Al-arabiyya",
                            "Al-huruf",
                            "Al-kitaba",
                            "Alhadith",
                            "Ulumul Amma",
                            "RNV",
                            "PVS",
                            "Hausa",
                        ],
                        'code'=>'S1O'
                    ]
                ]
            ]
        ];
        foreach($sections as $section){
            $newSection = Section::firstOrCreate(['name'=>$section['name']]);
            foreach($section['classes'] as $class){
                $newClass = $newSection->sectionClasses()->create(['code'=>$class['code'],'name'=>$class['name']]);
                foreach($class['subjects'] as $subject){
                    $newSubject = Subject::firstOrCreate(['name'=>$subject]);
                    $newSubject->sectionClassSubjects()->create(['name'=>$newSubject->name,'section_class_id'=>$newClass->id]);
                }
            }
        }
    }
}
